/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HomaniJavaProject;

import javax.swing.JOptionPane;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int CreditDays = 30;
        JOptionPane.showMessageDialog(null, " " + CreditDays);
        JOptionPane.showMessageDialog(null, "Every bill is due in "+ CreditDays + " days ");
    }
}
   
